### ISSUE TITLE
Unable to list branches for repository

### ISSUE THREAD

**Issue by nordsmetal** [dka23/gitlab-github-proxy#20]
I trying to integrate the glghproxy with our JIRA, and Gitlab, the same error happens when I try to refresh a repository from JIRA both on gitlab version 8.9.11, or with gitlab 9.3.0
```
glghproxy_1  | java.io.FileNotFoundException: https://gitlab.xxx.com/api/v3/projects/test%2Fjiratest/repository/branches/?access_token=xxx
glghproxy_1  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
glghproxy_1  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
glghproxy_1  | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
glghproxy_1  | 	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:287)
glghproxy_1  | 	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:124)
glghproxy_1  | 	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:96)
glghproxy_1  | 	at org.gitlab.api.GitlabAPI.getBranches(GitlabAPI.java:777)
glghproxy_1  | 	at com.dkaedv.glghproxy.controller.ReposController.getBranches(ReposController.java:69)
glghproxy_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
glghproxy_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
glghproxy_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
glghproxy_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
glghproxy_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
glghproxy_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
glghproxy_1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
glghproxy_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
glghproxy_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
glghproxy_1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
glghproxy_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
glghproxy_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
glghproxy_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
glghproxy_1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
glghproxy_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
glghproxy_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
glghproxy_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
glghproxy_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
glghproxy_1  | 	at com.dkaedv.glghproxy.LoggingFilter.doFilter(LoggingFilter.java:34)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
glghproxy_1  | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
glghproxy_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
glghproxy_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
glghproxy_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
glghproxy_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
glghproxy_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
glghproxy_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
glghproxy_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
glghproxy_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
glghproxy_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
glghproxy_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
glghproxy_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
glghproxy_1  | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
glghproxy_1  | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
glghproxy_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
glghproxy_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
glghproxy_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
glghproxy_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
glghproxy_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
glghproxy_1  | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nordsmetal** [comment]
false report, apache2 configuration was bad, it missed that property:
AllowEncodedSlashes NoDecode
